### PR TITLE
License correction

### PR DESCRIPTION
**Pull request by dpark12300**
Updated license to MIT

### CODE REVIEW

**Comment by twitchyliquid64** [comment]
The license on the linked Thingiverse page is not MIT - can you link me to where the author has relicensed it?

**Comment by dpark12300** [comment]
https://thangs.com/designer/ZackFreedman/3d-model/Gridfinity%20Baseplates-60925

Below download buttons

**Comment by twitchyliquid64** [comment]
Thats Gridfinity, but your PR updated the license in the sentence describing Alexander Chappels' Assortment System

**Comment by twitchyliquid64** [comment]
I don't think we mention the license of Gridfinity - you are welcome to add a sentence (preferably with a link)

**Comment by dpark12300** [comment]
OK. There's an issue on this topic, so probably close that too.

**Pull request closed without merging**
